### PR TITLE
Update to work with Craft 3

### PR DESCRIPTION
**Pull request by jdsdev**
I've updated Embedder to work with Craft 3. The docs and name spacing could probably use a once over if you want to publish to packagist.

### CODE REVIEW

**Comment by A-P** [comment]
Thanks for all of your work on this! It's been a while since I've been active in the Craft world - is this backward compatible with previous versions, or does it need to be maintained as a separate branch?

**Comment by jdsdev** [comment]
Thanks for all of your work as well! Clearly I've found the plugin useful enough to bring everything up to date. Unfortunately Craft 3 plugins aren't backward compatible. The standard practice seems to be to put the Craft 2 version in a separate branch.

I'm installing embedder through a reference to my repository on GitHub, but to make it more accessible to the community it would be better to publish the plugin to packagist and/or the Craft 3 plugin store.

**Comment by bossanova808** [comment]
Any updates on this?  Would be great to see this one in the plugin store as it's more comprehensive than alternatives.  Perhaps @jdsdev you could take over as maintainer???

**Comment by jdsdev** [comment]
If @A-P is okay with it, I could takeover. I'd want to change to the MIT license, and I could publish my branch to Packagist. As it stands right now, I've been using my branch without any issues for most of the year. If you know how to add a git repo to composer it should work fine.

**Comment by A-P** [comment]
@nvilus Pinkston Digital is technically the owner of this - totally up to you what you want to do with it.

**Comment by bossanova808** [comment]
Hi Folks

This (Craft 3 version) - seems to have suddenly dropped off the face of the earth - what has happened?

```
Loading composer repositories with package information                                                                                                                                                                           
  [Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of https://github.com/jdsdev/Embedder.git, could not load a package from it.
```

**Comment by jdsdev** [comment]
That's because I was handed control of the repository, but GitHub required me to remove my fork first. I'm planning to publish the updated Embedder under jdsdev/craft-embedder instead of ap/craft-embedder, which I used for the fork, and make it a more official 2.0. I just didn't have time immediately after the project was handed to me, but I'll have the update published by the end of today, and I should have it on Packagist by the end of the week. Apologies for the delay!

**Comment by bossanova808** [comment]
No worries, just blew up my composer update but what else is new ;)

No major hurry, thanks for taking it over!

**Comment by jdsdev** [comment]
Just got this published and added to Packagist, sorry that it took a bit longer than anticipated. You should be able to `composer remove ap/craft-embedder` now and `composer require jdsdev/craft-embedder`.

**Comment by bossanova808** [comment]
Yep seems all good here now with that - thanks so much!

**Pull request closed without merging**
