### PR TITLE
adds embed url to exposed variable

### PR DESCRIPTION
**Pull request by kotyy**
address #14

### CODE REVIEW

**Comment by sethburtonhall** [comment]
It seems that video_url does not exist. I am running **Embedder 0.9.4**

I am getting this error

```
Key "video_url" for array with keys "video_title, embed_code, video_author, video_author_url, video_thumbnail, video_mediumres, video_highres, video_description" does not exist.
```

when calling this template code
`{{ video.video_url }}`

**Comment by sethburtonhall** [comment]
After diving into the plugin code I realized that [this](https://github.com/A-P/Embedder/pull/15/commits/3e096409b0462a8718a9323f6a7c04472a9242b5) line of code was not present so I added it manually, but the returned url format is:

`http://www.youtube.com/oembed?format=xml&iframe=1&scheme=https&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdLLxGlcrJrk&maxwidth=560&maxheight=315`

when I was expecting something simpler like so: `https://www.youtube.com/embed/dLLxGlcrJrk`

Any thoughts?

**Comment by kotyy** [comment]
@middle8media This merge request was never accepted. 

But IIRC, my goal here was to create my own iframe and just needed the full embed URL with its parameters encoded in it. 

It looks like you might be supplying some parameters that are being added to the URL... and also, there might be some added by the plugin itself -- I don't remember.

**Comment by sethburtonhall** [comment]
Thanks @kotyy

**Pull request closed without merging**
